# Generated by Django 4.2.3 on 2023-08-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='myapp.grupo'),
        ),
    ]
