# Generated by Django 4.2.3 on 2023-08-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_equipo_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='numero_grupos',
            field=models.IntegerField(default=0),
        ),
    ]
