# Generated by Django 4.2.3 on 2023-08-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_competencia_numero_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
